# Generated by Django 5.2 on 2025-04-27 11:03

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='invite_token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=255, unique=True),
        ),
    ]
